### ISSUE TITLE
Simplify sample to run in dev mode out of the box

### ISSUE THREAD

**Issue by fredrik-lundin** [ActiveLogin/ActiveLogin.Authentication#10]
To be able to run the samples in dev mode, there are a couple of manual steps that need to be fixed before it can run properly. 

1. Missing certificates
The `IdentityServerSample` project expects two certificates to exist in the `/Certificates` folder even though you don't need them in dev mode.

2. Authority URL mismatch  
The port that the `IdentityServerSample` project will start on does not match the authority URL that the `MvcClientSample` expects.

We might want to look into making some better defaults to make the samples work out of the box (pure f5 experience ✌).

**Comment by nikolaykrondev** [comment]
Thanks @fredrik-lundin, I am already working on it ;)

**Comment by fredrik-lundin** [comment]
@nikolaykrondev I created a PR (#12) for this myself now. Have a look if it's something that could be of interest. If not, I'll wait for your to land :)

**Comment by PeterOrneholm** [comment]
Fixed in #12
