### ISSUE TITLE
BankId login page isn't supported in Internet Explorer 11

### ISSUE THREAD

**Issue by martinsjolanders** [ActiveLogin/ActiveLogin.Authentication#101]
IE11 don't have the required window.fetch and a polyfill is needed for those that wants to support it.

**What area is it related to**
Source

**To Reproduce**
1. Go to /account/login
2. Click on BankId(Other Device)
3.  A message stating "Your browser does not have the features required to use this login page." is showed.

**Expected behavior**
Page shows input for Personal Number and Sign In Button

**Screenshots**
![image](https://user-images.githubusercontent.com/13886506/53730659-e0cc6500-3e78-11e9-9bac-3d18357af7f5.png)

**Desktop (please complete the following information):**
 - Win 10
 - IE
 - 11

**Comment by fredrik-lundin** [comment]
A solution would be to just include the polyfill out of the box I guess? We can even make a code check for `window.fetch` and load the polyfill dynamically if needed.

Are there any considerations we should take, that might complicate things, or is this as straight forward as it seems?

**Comment by PeterOrneholm** [comment]
> A solution would be to just include the polyfill out of the box I guess? We can even make a code check for `window.fetch` and load the polyfill dynamically if needed.

I've considered it, but would like to avoid it. Active Login UI is rendered in the context of the current app, so when IE11 needs to be supported, such polyfill might already be available. Also, we would need to choose one specific and I'd like to not take dependencies on to many external stuff, as these usually are opinionated. Especiially in the cases when you don't need to support IE11. It seems alot are using this for logging in through an app, and then Chrome/Safari are the only browsers they need to support.

Adding a FAQ for this is my suggestion, and there we could point to one specific polyfill that people can use. Maybe also updating our sample with this.

**Comment by fredrik-lundin** [comment]
@PeterOrneholm I think you are right - we probably shouldn't include the polyfill by default. I've looked around some other projects, and it seems to be common practice **not** to include it.

What we probably should do is have a section about browser compatibility/supported browsers in our readme file, where information about polyfills needed for older browsers should be included.
