### ISSUE TITLE
Use feature "Static assets in Razor class libraries" in ASP.NET Core 3

### ISSUE THREAD

**Issue by PeterOrneholm** [ActiveLogin/ActiveLogin.Authentication#108]
**Is your feature request related to a problem? Please describe.**
Currently we inline / embed styles and scripts as ASP.NET Core 2.X does not provide a good way to reference static assets

**What area is it related to**
BankID

**Describe the solution you'd like**
In ASP.NET Core 3, preview 6 the feature to reference [Static assets (like styles and scripts) in Razor class libraries](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/) was introduced. We should try this solution.

**Additional context**
.NET Core 3 also introduces a new, faster JSON implementation, but this will require our API wrappers to target .NET Standard 2.1 and leave out .NET Framework etc. We won't use this feature now.

**Comment by span** [comment]
Is this something you would like help with before releasing 3.0.0?

**Comment by PeterOrneholm** [comment]
> Is this something you would like help with before releasing 3.0.0?

I haven't really decided myself if this is what I want to do. We have so little JS/CSS that embedding them might get better perf and we don't need to care about caches, which always is an issue otherwise.

I would vote for putting it on hold for now, if you don't convince me it's a super nice idea :)

**Comment by span** [comment]
Lol, it does not seems super important to me currently. I would put it on hold until the sun shines again.

**Comment by PeterOrneholm** [comment]
Closed as (maybe) part of #162 instead.
