### ISSUE TITLE
Upgrade to ASP.NET Core 3

### ISSUE THREAD

**Issue by PeterOrneholm** [ActiveLogin/ActiveLogin.Authentication#109]
**Is your feature request related to a problem? Please describe.**
To support users running latest version of ASP.NET Core, we should upgrade our package.

**What area is it related to**
BankID

**Describe the solution you'd like**
Upgrade to ASP.NET Core 3 and make sure it works. Find any changes done to the pipeline.

**Comment by span** [comment]
I notice this change went from targeting `.netstandard2.0` to `.netcoreapp3.0`.

Is there any reason you went from "standard" to core? Will `.netstandard2.1` wont work?

I'm thinking about potential xamarin integrations etc. that is only possible if targeting .netstandard.

**Comment by PeterOrneholm** [comment]
> I notice this change went from targeting `.netstandard2.0` to `.netcoreapp3.0`. Is there any reason you went from "standard" to "core"?

Good question! I didn't have time to document my findings when doing this, so let's do it now.

My intention was to not make this a breaking change, and keep targeting `netstandard2.0` but turned out not to work/not be optimal. The main reason is that in thr `*.AspNetCore` packages we do have dependencies on MVC. In ASP.NET Core <= 2.X MVC was distributed as a [NuGet package }(https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc/), but from 3.0.0 it's part of the framework, so you can't really reference it in the same way. My findings was that, even though most of the stuff seemed to work when referencing the old package from 3.0.0 runtime, I did get a ton of issues with incompatible versions of DLL:s etc.

Then I started looking into what Microsoft does, and they have changed their template and [their own packages](https://www.nuget.org/packages/Microsoft.AspNetCore.Identity.UI) (Razor class libraries) to target `.netcoreapp3.0` instead of `.netstandard`.

The documentation is quite bad on this very topic, but I did find out that if you create a new Razor Class Library (that we uses) in 3.00, it will target `.netstandard` by default, but only if you don't need support for pages/views (which we do). Once you supply that option, like this

```cmd
dotnet new razorclasslib -support-pages-and-views
```

It will instead target `.netcoreapp3.0`. So, the combination of the massive issues I had to get it to work with standard (I'm not even sure if it's a supported scenario) with that Microsoft follows this path, that's what I think we should aim for.

That beeing said, the API wrappers will still target `.netstandard2.0` and can be used form wherever that is supported. Even though it's technically possible to use from Xamarin, It's against the BankID agreement. Under [5 Technical requirements - RFT8](https://www.bankid.com/assets/bankid/rp/bankid-relying-party-guidelines-v3.2.2.pdf) it states:

> RP must contact BankID’s web service API from RP’s backend server. RP must NOT contact
BankID’s web service API from RP’s client app.

Hope this clarifies the decision :)
