### ISSUE TITLE
Add support for "Remember me"

### ISSUE THREAD

**Issue by PeterOrneholm** [ActiveLogin/ActiveLogin.Authentication#118]
**Is your feature request related to a problem? Please describe.**
At the moment, if the user is logging in from another device, he/she needs to fill in the Personal Identity Number on every new sign in. We could persist the personal identity number for that user.

**What area is it related to**
BankID

**Describe the solution you'd like**
For security and integrity reasons, I don't want to store the PIN on the local computer. Instead I'm proposing to use some server side store and store a token in a cookie that references the PIN. Potentially we can store the PIN encrypted using .NET Core Data Protector, depending on how long lived that data can be.

It should be opt in to enable such feature for the user.

**Comment by smuda** [comment]
Don't use any PIN at all and display a QR instead. See chapter 4 in [BankID Relying Party Guidelines](https://www.bankid.com/assets/bankid/rp/bankid-relying-party-guidelines-v3.2.2.pdf).

This will both enhance the user experience (no need to enter personal number) and security (binding information channel to security channel)

**Comment by PeterOrneholm** [comment]
> Don't use any PIN at all and display a QR instead. See chapter 4 in [BankID Relying Party Guidelines](https://www.bankid.com/assets/bankid/rp/bankid-relying-party-guidelines-v3.2.2.pdf).
> 
> This will both enhance the user experience (no need to enter personal number) and security (binding information channel to security channel)

Great input @smuda! Thanks for pointing that out. We already have an issue on implementing QR support, so I'll priorize that.
https://github.com/ActiveLogin/ActiveLogin.Authentication/issues/19
