### ISSUE TITLE
Azure KeyVault certificate path is misleading

### ISSUE THREAD

**Issue by span** [ActiveLogin/ActiveLogin.Authentication#127]
**Describe the bug**
Azure key vault certificate client requests a secret and not a certificate. This means the object url that can be copied from keyvault is incorrect and requires manual handling.

**What area is it related to**
Azure keyvault

**To Reproduce**
1. Go to Keyvault Certificates
2. Copy certificate identifier
3. Configure client certificate with the identifier
4. Initiate an authentication request
5. After challenge, view this error: 

```
[2019-10-16 10:34:39 Error] Microsoft.AspNetCore.Server.Kestrel
Connection id "0HLQI2EKHAAJJ", Request id "0HLQI2EKHAAJJ:00000004": An unhandled exception was thrown by the application.
System.ArgumentException: Invalid ObjectIdentifier: https://[KEYVAULT]/certificates/[CERTIFICATE NAME]/[IDENTIFIER]. segment [1] should be 'secrets/', found 'certificates/'
   at Microsoft.Azure.KeyVault.ObjectIdentifier..ctor(String collection, String identifier)
   at Microsoft.Azure.KeyVault.SecretIdentifier..ctor(String identifier)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretAsync(IKeyVaultClient operations, String secretIdentifier, CancellationToken cancellationToken)
   at ActiveLogin.Authentication.BankId.AspNetCore.Azure.KeyVault.AzureKeyVaultCertificateClient.GetX509Certificate2Async(String keyVaultSecretIdentifier) in [PROJECT PATH]/ActiveLogin.Authentication/src/ActiveLogin.Authentication.BankId.AspNetCore.Azure/KeyVault/AzureKeyVaultCertificateClient.cs:line 69
```

> segment [1] should be 'secrets/', found 'certificates/'

**Expected behavior**
I expect the action to work and not trigger an error

**NuGet package version**
Latest master

**Runtime version**
.net core 2.2

**Causing code**
The use of `GetSecretAsync` in `AzureKeyVaultCertificateClient` on line 69:

```
var secret = await _keyVaultClient
    .GetSecretAsync(keyVaultSecretIdentifier).ConfigureAwait(false);
```

**Proposed fix**
Use `GetCertificateAsync` to retreive certificates. Perhaps getting the certificate can be made smart so it accepts both `secrets` and `certificates`.

**Regressions**
This will probably be a breaking change since it affects configured strings. If it is fixed, it should be fixed in a Major release, e.g. 3.0. There is also some documentation related to this that would need updating. The documentation is correct on how to set up the identifier using `secrets` but I still found this confusing enough to report it.

**Comment by PeterOrneholm** [comment]
Thanks for the detailed issue! I know I've been thinking about this, and I can remember using that call, but getting incorrect data back. Will try and see what issue I had.

Added 3.0.0 milestone, because as you say if we implement it, it's a breaking change.

**Comment by span** [comment]
Closing this since PR is closed as well.
