### ISSUE TITLE
Use AngleSharp in tests

### ISSUE THREAD

**Issue by span** [ActiveLogin/ActiveLogin.Authentication#147]
From @PeterOrneholm in #138 

>  I recently stumbled upon AngleSharp for parsing HTML in C#. Microsoft seems to recommend it here: https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.0
>
> If I get it right, you can parse the DOM using the lib, query for the element you like and check a specific prop. That would make our tests less fragile.

This is a great idea for the tests and will make it much easier to test the different paths in the authentication flow.

**Comment by span** [comment]
Perhaps a refactor of the tests could be part of this to prepare it for AngleSharp as well. Currently there is a lot of code duplication.

I'm sure we could split it up in a few different test classes depending on scenarios with a few helpers.

**Comment by PeterOrneholm** [comment]
We should do this :) I think it's a two step thing. First introduce AngleSharp to replace the places where we check for exact strings of HTML, after that we can look at a refactor of the test suite.

**Comment by span** [comment]
This looks like fun. I'm packed with other things to do at the moment though 😢
