### ISSUE TITLE
Clarify in documentation on why we need to use /secrets/ in when fetching certificates

### ISSUE THREAD

**Issue by span** [ActiveLogin/ActiveLogin.Authentication#148]
When we fetch client certificates from key vault we are using the `GetSecretAsync` method as described in #144 .

We should clarify why we need to do it this way in the documentation.

A few links: 

Official documentation (very extensive)
https://docs.microsoft.com/en-gb/azure/key-vault/about-keys-secrets-and-certificates#BKMK_CompositionOfCertificate

Problem solved in blog:
https://azidentity.azurewebsites.net/post/2018/07/03/azure-key-vault-certificates-are-secrets

**Comment by PeterOrneholm** [comment]
Fixed in #149
