### ISSUE TITLE
Display PIN input for unsupported browsers

### ISSUE THREAD

**Issue by span** [ActiveLogin/ActiveLogin.Authentication#159]
**Describe the bug**
When using "same device" authentication some browsers display the `UnsupportedBrowserErrorMessage`.

**What area is it related to**
BankID

**To Reproduce**
1. Use unsupported browser
2. Choose same device authentication

**Expected behavior**
The PIN input to be shown.

**NuGet package version**
Latest master

**Smartphone (please complete the following information):**
- iPad
- IOS 9
- Safari

**Additional context**
Instead of showing the "unsupported" message, I suggest we show the PIN input to allow the user to at least initiate the process and hopefully complete it by launching the app manually.

Since I am pretty sure Safari on the iPad supports session storage  it seems the issue is with "fetch". Is it not supported for older browsers? Is there an alternative way of solving this?

**Comment by PeterOrneholm** [comment]
The `` is shown if the browser lacks any of the features needed to run the JavaScript code on the client, we do rely on these features:

- Fetch (https://caniuse.com/#feat=fetch)
- SessionStorage (https://caniuse.com/#feat=mdn-api_window_sessionstorage)

It seems like Safari on iOS 9 lacks Fetch support:
![image](https://user-images.githubusercontent.com/1662918/68989367-0aca8980-0846-11ea-9bc3-ad150a5fa96e.png)

In our readme for BankID we do recomend a Polyfill for Fetch if you support older browsers:
https://github.com/ActiveLogin/ActiveLogin.Authentication/blob/master/docs/getting-started-bankid.md#what-browsers-do-you-support

If you use such polyfill, does it work for you?

(I just realized we have used the wrong file for our polyfills in our samples, will fix that...)

**Comment by PeterOrneholm** [comment]
@span: You can now try https://al-samples-identityserver.azurewebsites.net/ that uses the correct polyfill for fetch, does it work?

**Comment by PeterOrneholm** [comment]
Did you have time to try this out @span?

**Comment by span** [comment]
Sorry, i have not had the time to have a look at this yet. I'll have a look today and close it since I'm sure you are correct :)

**Comment by span** [comment]
I've tried a couple of times but demo environment seems down. I'm sure you are correct though and will close this for now. I'll re-open if issue persists.

**Comment by PeterOrneholm** [comment]
Ahh, I forgot to package the framework. Azure App Service does not run Core 3.1, so will need to bundle. Will fix that. Thanks for pointing out!

**Comment by PeterOrneholm** [comment]
It's up and running now @span if you want to give it a try :)

**Comment by span** [comment]
I still get the message on my old ipad. Perhaps it is just too old :P

**Comment by PeterOrneholm** [comment]
My bad, I had placed the polyfill AFTER the use of `fetch`... Just merged a fix to master and should be released to demo environment any minute. Your iPad isn't to old :)

**Comment by span** [comment]
Tried again today and it worked flawlessly 🙌
