### ISSUE TITLE
EndUserIp not accepted by BankID API

### ISSUE THREAD

**Issue by magohl** [ActiveLogin/ActiveLogin.Authentication#213]
**Describe the bug**
In certain hosting environments the response from GetEndUserIp() are not accepted by BankID as valid endUserIp.

Running in docker/linux container on Windows 10 'HttpContext.Connection.RemoteIpAddress' can return an IPv4 addresses mapped to IPv6 (eg. ::ffff:172.19.0.1) which fails with BankID error 'Invalid endUserIp'.

BankID relying party guidelines states "IPv4 and IPv6 is allowed" but does not seem to accept an IPv4 addresses mapped to IPv6.

**What area is it related to**
BankID

**To Reproduce**
1. Run application in docker/linux (Docker 2.1.7.0, Windows 10 19041) with base image mcr.microsoft.com/dotnet/core/aspnet:3.1
2. Login using BankID
3. Exception : ActiveLogin.Authentication.BankId.Api.BankIdApiException: InvalidParameters: Invalid endUserIp

**Expected behavior**
No exception

**NuGet package version**
3.0.0-beta-2

**Runtime version**
Microsoft.AspNetCore.App 3.1.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 79

**Additional context**
Suggested fix is a minor change GetEndUserIp() to use the IsIPv4MappedToIPv6 property to decide if the address should be returned in IPv4 format or not.

**Comment by PeterOrneholm** [comment]
Hi @magohl! Good catch.
We had an issue also related to endUserIp some time ago:
https://github.com/ActiveLogin/ActiveLogin.Authentication/issues/152
https://github.com/ActiveLogin/ActiveLogin.Authentication/pull/153

In that case we closed it and recommend configuring the pipeline in ASP.NET Core instead, from my quick look, I don't think that would do it in this case, right?

`IsIPv4MappedToIPv6` looks like something we should look into. Haven't dug into the details yet, but do you know if there are any built in class for parsing that IP and only get the IpV4 part (which I geuss is the public IP in this case)?

**Comment by PeterOrneholm** [comment]
Given that we've had a few issues with EndUserIp, I'm thinking it might be an idea for our 3.1 release to make that an interface anyone can override. Running in containers and behind proxies seems to have a few special cases.

**Comment by magohl** [comment]
I made this change on my side and it has worked great both in the docker/linux and directly on windows.

```
private string GetEndUserIp()
{
    var remoteIp = HttpContext.Connection.RemoteIpAddress;
    return (remoteIp.IsIPv4MappedToIPv6 ? remoteIp.MapToIPv4().ToString() : remoteIp.ToString());
}
```

**Comment by PeterOrneholm** [comment]
Great, thanks for the code @magohl!

We will release 3.0.0 any day, we are in RC1 right now and don't want to make this change until that is released. But we can release 3.0.1 shortly after.

I can fix this, but feel free to make a PR so you get the credit.
