### ISSUE TITLE
Clarify in documentation on requirements when using QR-Code on docker/linux

### ISSUE THREAD

**Issue by magohl** [ActiveLogin/ActiveLogin.Authentication#218]
Using QRCoder package when hosted in Docker/Linux with Microsoft standard docker images requires the additional package 'libgdiplus' to be installed as part of the Dockerfile.

Maybe add a short note in the documentation with the command needed to install 'libgdiplus' in the Dockerfile.

**Comment by PeterOrneholm** [comment]
Good point! We should add this. Do you want to make a PR yourself? You probably have a better understanding of the details than me.

**Comment by magohl** [comment]
No problem, i will add it.

Do you think it belongs in the FAQ or should we put it under the current "Note: .UseQrCoderQrCodeGenerator() requires..."?

**Comment by PeterOrneholm** [comment]
> Do you think it belongs in the FAQ or should we put it under the current "Note: .UseQrCoderQrCodeGenerator() requires..."?

I would vote for a FAQ on something like "What dependencies do I need If I run Active Login in a Docker container?" And then mention the one you found.

Note, don't forget to add the FAQ to the Table of Contents at thw top as well.
