### ISSUE TITLE
How To Implement In Flutter

### ISSUE THREAD

**Issue by wifirevaithi** [ActiveLogin/ActiveLogin.Authentication#225]
hi,

Someone help me out to integrate bankid login with firebase

**Comment by PeterOrneholm** [comment]
Hi @wifirevaithi!

Active Login is a library to get started with BankID for .NET and does not have any support for Flutter/Firebase. If you have experience with .NET and Identity Server, you could use that to make Flutter talk OIDC to Identity Server, but we don't provide any free support on that in addition on what's already available in our docs.

Here are the technical docs from BankID to implement BankID yourself in the platform (Flutter/Firebase) you use:
https://www.bankid.com/assets/bankid/rp/bankid-relying-party-guidelines-v3.2.2.pdf

__NOTE:__ You are not allowed to implement BankID right from the app (Flutter), it needs to be backed by a backend that can host the certificate.

Closing this issue now, as it's not related to Active Login.

**Comment by wifirevaithi** [comment]
Thanks for the response.i need to create my own api and have to use in my flutter app right?

**Comment by PeterOrneholm** [comment]
Yes, you need some kind of backend API. That could be Active Login, if you know .NET or implemented in the language of your choice.

**Comment by wifirevaithi** [comment]
no,i don't know .net only php
