### ISSUE TITLE
Add ASP.NET Health Check for BankID API

### ISSUE THREAD

**Issue by PeterOrneholm** [ActiveLogin/ActiveLogin.Authentication#234]
**Is your feature request related to a problem? Please describe.**
BankID is very stable, but does sometimes go down. It just happened a few days ago due to a DDos attack. ASP.NET Core have a concept for standardized [health monitoring](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/monitor-app-health) and we could build a health check that verifies that BankID is available.

**What area is it related to**
- BankID

**Describe the solution you'd like**
The BankID API:s requires a client certificate to give an answer, you can't just ping them. So suggested solution is to write a health check that will initiate a login (`/auth`), ensure you get back a token (`OrderRef`)  and then immediately cancel (`/cancel`) the session. If you are able to retrieve an OrderRef BankID should be treated as healthy.

**Additional context**
I'd vote for this reusing all implementations that should already be available because you've called `.AddBankId()` on the authentication builder. So basically a solution would look something like this:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    //...
    services.AddHealthChecks()
        .AddBankId();
}
```

That just use the BankID client that was registered. If there is a need for it, in  a future version we could have a look at taking the environment and certificates as parameters.

**Comment by nikolaykrondev** [comment]
Nice idea, but won't it be that we will be also the reason for DDoS if people use it wrong? :) 
Plus, if I remember correct, in the contract with banks when you order BankId service you pay for amount of requests, which leads again to exceeding the limit if you use health checks extremely often (like in dashboards)

**Comment by PeterOrneholm** [comment]
> Nice idea, but won't it be that we will be also the reason for DDoS if people use it wrong? :)

Yes, that is something we would need to consider, and maybe throttle it to some maximum checks/minute. But still, a real world application, like the large financial institutes probably have thousands of real logins/second, so if we check once a minute shouldn't be an issue.

> If I remember correct, in the contract with banks when you order BankId service you pay for amount of requests, which leads again to exceeding the limit if you use health checks extremely often (like in dashboards).

Very valid point. I haven't found any info on if you pay for each started login, or only for those that succeeds. With my suggestion above, we would only start and then cancel it - and maybe that does not need to cost any money. I'll try to find out more about this. Good input!

**Comment by PeterOrneholm** [comment]
I've had a discussion with BankID around this. It's not recommended to do such monitoring. Therefore I'll close this issue.

For BankID status, this page should be used:
https://www.bankid.com/bankid-i-dina-tjanster/bankid-status
