### ISSUE TITLE
Strong name assemblies

### ISSUE THREAD

**Issue by PeterOrneholm** [ActiveLogin/ActiveLogin.Authentication#25]
Inspired by [Microsoft Open-source library guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming
) we should strong name the assemblies to support beeing referenced from other strong named assemblies.

> CONSIDER strong naming your library's assemblies.

**Comment by Zonnex** [comment]
For this one, I assume we want to strongly named all 6 projects?
