### ISSUE TITLE
New Architecture

### ISSUE THREAD

**Issue by PeterOrneholm** [ActiveLogin/ActiveLogin.Authentication#257]
**Is your feature request related to a problem? Please describe.**
Active Login have been existing for a few years now and since v1 we have added a bunch of features, fixed loads of bugs and improved code quality and documentation. We are about to release v4 and with every major release we have done breaking changes when those have been necessary. So far tough, the core architecture have stayed the same and the breaking changes have mostly affected those who had been doing customizations and implemented their own interfaces.

We now have a few issues and ideas for improvements that would benefit a rethinking of the architecture. Making some things more modular, moving things between packages and so on. This issue is supposed to keep track of this process, and will link to more specific issues when that is necessary.

**What area is it related to**
Main focus will be BankId, GrandId might follow later on.

**Describe the solution you'd like**
Here are a few ideas we should have in mind doing this:

- Allow for a (better) Multi tenancy solution (#236)
- Be built for .NET 5 and any conventions that this might infer (drop *Core?) (##248)
- Allow for easier usage of the BankID API client as a standalone client (#235)
- Refactor controllers to have as little as possible logic in them (#199)
  - Would allow for easier BankID Singing (#110)
- Refactor front end code: Separate files, TypeScript, pluggable (#162)
- Avoid user agent detection (#264)

**Additional context**
This issue will live for some time and should be implemented by multiple PR:s.

Input is very welcome.

**Comment by dejancg** [comment]
Hi @PeterOrneholm! This is some good news. Hopefully you will consider using `IOptions` to configure options for BankId and GrandId when using with ASP.NET Core, so these can be configured on a per-request basis. Currently, we allow our clients to add their own external identity providers through the user interface, and settings are saved to the database. While the `IOptions` pattern made this possible for most provider types (OIDC, WS-Federation, SAML), when adding BankId or GrandId, clients are required to restart their IdentityServer instances for changes to take effect. Please take a closer look at this pattern here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0 and for a practical example on how we use this pattern to accomplish having dynamic authentication schemes, please take a look at this StackOverflow question: https://stackoverflow.com/q/61279775/828023 and my answer: https://stackoverflow.com/a/61287736/828023

**Comment by PeterOrneholm** [comment]
Great idea @dejancg. That we should do.
Can't promise when work will be started on this.

Is it urgent for you?

**Comment by dejancg** [comment]
Hey @PeterOrneholm.
We have started the process of rewriting what's required and updating from .NET4 to .NET5. It will take a while, but not that it's not urgent either. Do you have any plans as to when 5.0.0 release should roll out?

**Comment by PeterOrneholm** [comment]
> Do you have any plans as to when 5.0.0 release should roll out?

At the moment, we don't have any case on our own where we need these changes, so it's not top priority, so don't have any estimated date for it. If it's important for you, and you are willing to sponsor part of such development, it will happen faster.

**Comment by dejancg** [comment]
Just so we're clear, you don't have any estimated date for 5.0.0, or you don't have any estimated date for IOptions pattern implementation?

**Comment by PeterOrneholm** [comment]
The IOptions pattern will be part of new architechture, so those dates will align. It will be a breaking change, so can't introduce it before new major release.

**Comment by dejancg** [comment]
Thanks for the clarification.
While this is not an urgent matter for us, it would be good to know some date or timeframe of the planned rollout in case we decide to wait, and the same information in case we decide to sponsor.

**Comment by PeterOrneholm** [comment]
The main ideas of this are now part of v6.
