### ISSUE TITLE
Missing parameter at Logout request

### ISSUE THREAD

**Issue by johansulau** [ActiveLogin/ActiveLogin.Authentication#265]
**Describe the bug**
There is a missing parameter in the Logout call for GrandID API.
The GrandID API requires 3 parameters for logout call, namely 
APIKey, authenticateServiceKey and sessionID. The authenticateServiceKey parameter is missing in your call thus causing an error response.

**What area is it related to**
BankID, GrandID, API etc.

**To Reproduce**
1. Send a request with only two parameters to https://client-test.grandid.com/json1.1/Logout?apiKey={apikey}&sessionid={sessionid}
This will return an error response

**Expected behavior**
The call should be with three parameters like this
https://client-test.grandid.com/json1.1/Logout?apiKey={apikey}&authenticateServiceKey={authenticateservicekey}&sessionid={sessionid}
This will get the desired response

**Screenshots**

**NuGet package version**
3.0.0
**Runtime version**
 .NET Framework 4.8

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: Microsoft Edge

**Additional context**

**Comment by PeterOrneholm** [comment]
Thanks for pointing this out. Looks like they've added that, wasn't required when we made the first implementation. I'll fix it.

**Comment by PeterOrneholm** [comment]
I've just merged a fix into master and soon there will be a beta out on NuGet for you to try @johansulau.

**Comment by johansulau** [comment]
Great, thanks!
