### ISSUE TITLE
Add support for Animated QR codes

### ISSUE THREAD

**Issue by PeterOrneholm** [ActiveLogin/ActiveLogin.Authentication#276]
**Is your feature request related to a problem? Please describe.**
Since API v5.1 you can support animated QR codes for additional security. See #275 for the API issue around this.
We should allow the user to use the animated QR codes.

**What area is it related to**
BankID

**Describe the solution you'd like**
I would have liked for the solution to be stateless, as Active Login is today, but as per my knowledge the animated QR codes is not possible to implement (in a safe way) without storing state on the server. Only one image can be generated at a time, needs to be done on the server and the server needs a secret. Therefore my suggestion is to make this feature optional (in case you can't or don't want to store state on the server). The state handling should be hidden behind an interface, but default to something built into ASP.NET Core.

**Additional context**
I've tried it out locally, so I have some working code.

**Comment by ellinge** [comment]
I looked into his now as well. How about using a encrypted object (machineKey) for the request instead? Then you could avoid state (or move it to the client for storage) without exposing the qrSecret?
{
   orderRef = ...
   qrToken = current  calculated
   qrRef = encrypted [
      (qrSecret),
      (randomNumber)
   ]
}

Then you could decrypt the qrSecret and calculate a new qrToken-response for the next image on the poll? There's some client libraries for generating qr codes on the client as well.

**Comment by ellinge** [comment]
Got this as a response from BankID (translated):
> 
> Thanks for your mail. The reason we do not want you to send qrStartSecret to the user's browser / user agent is because the browser cannot be considered secure. The risk is that malicious software is in it and that the software reveals qrStartSecret, which could result in the entire sequence of moving QR codes being recreated elsewhere.
> 
> If I have understood your description correctly, then you have made an effort to protect qrStartSecret in such a way that it is not exposed to the browser, and you live up to our recommendation that qrStartSecret should be a secret that is only shared between us and your service / server. Clever! We see a certain risk that you may have problems with the timing, because the algorithm is based on knowing the time that has passed since you received the first answer from us. It can probably be solved by including the start time in the blob that is sent back and forth. 

So should be safe as long as it's not able to be brute forced, which it shouldn't, as no data is encrypted that is known.
