### ISSUE TITLE
Missing field autostarttoken in class BankIdFederatedLoginResponse GrandId API

### ISSUE THREAD

**Issue by johansulau** [ActiveLogin/ActiveLogin.Authentication#280]
**Describe the bug**
When calling GrandId API using method BankIdFederatedLoginAsync with parameter showgui set to false you will recieve an autostarttoken instead of a redirecturl in the response from GrandId API. This is to be able to start the BankId App automatically on a mobile native app.
See GrandId documentation at https://docs.grandid.com/bankid#bankid-examples-bankid-for-apps
Therefore you should have a new field autostarttoken in your class BankIdFederatedLoginResponse

**What area is it related to**
BankID, GrandID, API etc.

**To Reproduce**
1. Make a call to GrandId API using BankIdFederatedLoginAsync with parameter ShowGui set to false passing along a personalIdentityNumber in the call.
2. In the reponse from GrandId API you should recieve an autostarttoken instead of a redirecturl
3.  in class BankIdFederatedLoginResponse theres no related field to autostarttoken thus you will never be able to grab it.

**Expected behavior**
you should be able to grab the autostarttoken from class BankIdFederatedLoginResponse

**Screenshots**

NuGet package version
3.0.0
Runtime version
.NET Framework 4.8

Desktop (please complete the following information):

OS: windows
Browser: Microsoft Edge
Additional context

**Comment by PeterOrneholm** [comment]
Hi @johansulau and thank for reporting this. I have relabeled this as enhancement because it's a new field we have not yet implemented.

GrandId is not the main focus for us, so we won't take action on this in the near future, but a PR according to our contribution guidelines would be merged. Would you be up for doing that?

**Comment by PeterOrneholm** [comment]
Closing this as we are dropping official support for GrandID and won't work on adding new features.
