### ISSUE TITLE
Dictionary<string, string> cannot be used for parameter 'postData'

### ISSUE THREAD

**Issue by Heichichi** [ActiveLogin/ActiveLogin.Authentication#283]
**Describe the bug**
Just downloaded the project and hit build, getting an error in GrandIdApiClient.cs:126

**What area is it related to**
GrandID PostFullResponseAndEnsureSuccess

**To Reproduce**
1. Download project
2. Change sdk version to newer (In my case 3.1.404 in global.json
3. Build

**Expected behavior**
It should build

**NuGet package version**
2.0.2

**Runtime version**
.NET Core SDK 3.1.404

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: not applicable
 - Version not applicable

**Additional context**
Error	CS8620	Argument of type 'Dictionary<string, string>' cannot be used for parameter 'postData' of type 'Dictionary<string, string?>' in 'Task<TResult> GrandIdHttpClientExtensions.PostAsync<TResult>(HttpClient httpClient, string url, Dictionary<string, string?> postData)' due to differences in the nullability of reference types.	ActiveLogin.Authentication.GrandId.Api

**Comment by PeterOrneholm** [comment]
Hi @Heichichi!

I haven't reproduced this yet, but your numbers don't add up to me.

NuGet package version 2.0.2 is bery old and master uses 4.0.0. Are you sure you are using 2.0.2?
What SDK / runtime version did you have before chaning to 3.1.404? In master we build each commit with 3.1.100 and that works at the moment.

I'll dig into the details when getting the bigger picture 👍 

/Peter

**Comment by PeterOrneholm** [comment]
Any answer to my question above @Heichichi? Otherwise I'll close this issue.
