### ISSUE TITLE
Support for .NET Framework 4.8 LTS

### ISSUE THREAD

**Issue by bemafred** [ActiveLogin/ActiveLogin.Authentication#284]
**Is your feature request related to a problem? Please describe.**
Legacy systems still on .NET Framework and adding support for BankID would benefit from targeting .NET Framework 4.8 LTS

**What area is it related to**
BankID, GrandID, API etc.

**Describe the solution you'd like**
A branch targeting .NET Framework 4.8 LTS and a corresponding a nuget package

**Describe alternatives you've considered**
Adhoc implementation targeting .NET Framework 4.8 LTS

**Comment by PeterOrneholm** [comment]
Hi @bemafred!

Thanks for asking.

We do have partial support for .NET Framework 4.8 already. The `ActiveLogin.Authentication.BankId.Api` package targets .NET Standard 2.0 and can therefore be consumed from .NET Framework 4.8. This package contains the API wrapper for the BankID API, but no UI.

For the UI parts, we do not have any official support for .NET Framework and won't release such support either. The primary reason being it's a minority of the cases that needs it and we want to spend the time where it brings the most value to the community.

Our recommendation for these scenarios is to run another site on .NET Core / .NET 5 with Identity Server + Active Login and federate to that one using Open ID Connect. 

If the Identity Server solution described above, for some reason, does not work out for you, we could make a tailor made implementation for the specific scenario on .NET Framework 4.8 on top of the API wrapper as part of our [commercial support](https://activelogin.net/).
