### ISSUE TITLE
Multi-tenant support for GrandId?

### ISSUE THREAD

**Issue by Markus-Code** [ActiveLogin/ActiveLogin.Authentication#285]
**Describe the bug**
Is there support in GrandId for multi-tenant? 

**What area is it related to**
GrandID

**To Reproduce**
Create a new .Net Core project, install dependencies, AddGrandId twice ( or more )

**Expected behavior**
An isolated provider per scheme/customer with different api-keys

**NuGet package version**
ActiveLogin.Authentication.GrandId.AspNetCore 4.0

**Runtime version**
.NET Core 3.1

**Desktop (please complete the following information):**
 - Windows
 - Chrome etc.

**Additional context**
Is there support for multi-tenancy when using GrandId?

**Comment by PeterOrneholm** [comment]
Hi @Markus-Code!

Multi tenancy support is something we have implemented and used ourselves, but only for the "native" BankID-provider. You can find the documentation for that here:
https://github.com/ActiveLogin/ActiveLogin.Authentication/blob/master/docs/getting-started-bankid.md#multi-tenant-scenario

For GrandID we do not have any official support for such and have no plans to implement it. In general, we have seen a decline in interest for GrandID and will be focusing our development efforts on the native client going forward.

If you are interested in trying to solve this yourself, here are some relevant places in the code:

https://github.com/ActiveLogin/ActiveLogin.Authentication/blob/master/src/ActiveLogin.Authentication.GrandId.AspNetCore/GrandIdBuilderEnvironmentExtensions.cs#L75

https://github.com/ActiveLogin/ActiveLogin.Authentication/blob/3f2b4482c2a1b9c62d376ef4a39824d1cb3485d7/src/ActiveLogin.Authentication.GrandId.Api/GrandIdApiClient.cs#L20

From the top of my head, I think that `GrandIdApiClientConfiguration` (which today contains static references to the keys) would have to be replaced with callback that given the current `HttpContext` would resolve the keys. To maintain backwards compatibility, we could provide an overload on the constructor that would take ethe `GrandIdApiClientConfiguration` as an input.

Would you be up for trying to solve this and send us a PR (following our [contribution guidelines] (https://github.com/ActiveLogin/ActiveLogin.Authentication/blob/master/CONTRIBUTING.md))?

I'll close this as this answers your question, If you want to implement it, please open another issue explaining your proposed solution.
