### ISSUE TITLE
PostData parameter mobileBankId=false actively denies mobilt bankid

### ISSUE THREAD

**Issue by peterdanielssonservicewell** [ActiveLogin/ActiveLogin.Authentication#294]
**Describe the bug**
In GrandIdApiClient.BankIdFederatedLoginAsync
The PostData parameter mobileBankId=false actively denies mobilt bankid. 
Since it is always set to false (from GrandIdBankIdOptions) it is not possible to login using mobilt bank id.

It is set from 
/// <summary>
/// If set to true, only mobile certificates will be allowed to be used (mobile apps).
/// </summary>
public bool RequireMobileBankId { get; } = false;

The description does not say it is actively denying when set to false.

**What area is it related to**
GrandID BankIdOtherDevice

**To Reproduce**
Start up ClientSample and Server sample
Select Grand Id (Other device)
Scan QR code -> "Felmeddelande i mobilen"

**Expected behavior**

**Screenshots**

**NuGet package version**
4.0.0

**Runtime version**
.NET Core 

**Additional context**
I have been in touch with Svensk E-identitet. They said not to send the mobileBankId=false.
I would lika a possibility to skip this parameter.

**Comment by PeterOrneholm** [comment]
Cool! Could you drop the people at Svensk E-identitet an email and ask them to confirm this behavior and ask them to update the docs to reflect this? If you do that I'll look at making it nullable :)

**Comment by PeterOrneholm** [comment]
Closing this as we are dropping official support for GrandID and won't work on adding new features.
