### ISSUE TITLE
Allow for custom handling when the state cookie is missing

### ISSUE THREAD

**Issue by PeterOrneholm** [ActiveLogin/ActiveLogin.Authentication#301]
**Is your feature request related to a problem? Please describe.**
As described in #298 we have found scenarios where the state cookie might be missing. Adding #300 would also introduce scenarios where state might be available but have expired.

We should handle that scenario in a way that it has some default implementation but is customizable for those who want/needs that.

**What area is it related to**
BankID

**Describe the solution you'd like**
Check in `BankIdController` > `Login` if the state cookie is still there and is valid. If not, let the injected handler handle it.

```csharp
if (IsInvalidStateCookie())
{
  if(unprotectedLoginOptions == null) {
    await _bankIdInvalidStateHandler.HandleAsync(context);
  } else {
   await _bankIdInvalidStateHandler.HandleAsync(context, unprotectedLoginOptions.CancelReturnUrl);
  }

    return;
}
```

A default implementation could use the cancelUrl, like this:

```csharp
public BankIdCancelUrlInvalidStateHandler : IBankIdInvalidStateHandler {
  public TaskHandleAsync(HttpContext context) {
    context.Response.Redirect("/");
  }

  public TaskHandleAsync(HttpContext context, string cancelReturnUrl) {
    context.Response.Redirect(cancelReturnUrl);
  }
}
```

**Comment by span** [comment]
Would love to see this. :+1:
