### ISSUE TITLE
Add support for userVisibleData, userNonVisibleData, userVisibleDataFormat on auth

### ISSUE THREAD

**Issue by PeterOrneholm** [ActiveLogin/ActiveLogin.Authentication#328]
**Is your feature request related to a problem? Please describe.**
Turns out BankID just released support for supplying data (visible and non visible) for auth. This had previously only been available for sign. We should add this to both the API wrapper but also making it possible to supply custom data per auth.

These fields have been added:
- `userVisibleData`
- `userNonVisibleData`
- `userVisibleDataFormat`

**What area is it related to**
API, UI

**Describe the solution you'd like**
For the API, something very similar to how auth works.

For the AspNet package I'm thinking some kind of interface you can plug into and given some context (not sure what is available right now, but HttpContext should be one of them) the function would be responsible for responding with that data.

The AuthRequest and SignRequest now seems to have exactly the same properties. I'd suggest making sure their constructors uses the same order for parameters. Maybe use a shared base class, not sure.

**Comment by equist** [comment]
For the AspNet package I belive two scenarios are very valid:
1. A static configured message in a setting that is "just" picked up and send. This would in many scenarios be enough and very simple to use when all you do is configure your text in Startup.cs.
2. A more dynamic way to pass the text. For example when ActiveLogin is used in an IdP (IdentityServer) different clients can have different intention of an identification. This is therefor controlled by the client is some way and the IdP implementation needs to be abel to pass this text to the BankId handler somehow.

**Comment by joanro123** [comment]
We made now a draft pull request to try to solve these issues:
https://github.com/ActiveLogin/ActiveLogin.Authentication/pull/340

We would appreciate feedback @equist if you want to see which changes we made.

**Comment by equist** [comment]
I don't know the code base in details, but wouldn't it be necessary to be able to pass BankIdAuthUserData with BankIdLoginOptions to be able to support the more dynamic setting of UserVisibleData (aka IdP scenario)? BankIdLoginOptions getting the data through AuthenticationProperties (like for CancelUrl).
How else should the dynamic setting of UserVisibleData be handled?

For the static configuration av UserVisibleData the solution looks good.

**Comment by PeterOrneholm** [comment]
I can see :) We are bout to write the docs for it, but that's not ready yet. 

The solution we have now, at its core, is that you can implement this interface yourself and be very flexible in an (for example) IdP scenario:
https://github.com/ActiveLogin/ActiveLogin.Authentication/blob/724154f6e7aa2297f6c92e989ed06fff296ab5dd/src/ActiveLogin.Authentication.BankId.AspNetCore/IBankIdAuthRequestUserDataResolver.cs

You will be handled all the context we know of, which is;
* HttpContext
* EndUserIp
* PersonalIdentityNumber (usually empty)
* Requirement (Any BankID Requirement set)

The important thing here is the HttpContext so that you, given the current tenant, you can customize the text. For example: Look at the current hostname, figure out for what tenant it is used for, and then customize the text.

Simple sample:
```csharp
    public class SampleUserDataResolver : IBankIdAuthRequestUserDataResolver
    {
        private static readonly BankIdAuthUserData _emptyAuthUserData = new();

        public BankIdAuthUserData GetUserData(BankIdAuthRequestContext authRequestContext, HttpContext httpContext)
        {
            if(httpContext.Abc = "def") {
              .....
            } else {
              .....
            }
        }
    }
```

That class would then be registered in the ASP.NET DI container after `.AddBankdId()` to override the default implementation.

One thing I realize is that we should make it async to allow for async data fetching, like looking up the text in a db or similar.

@joanro123 Can you make it async? Basically like this:

```csharp
Task<BankIdAuthUserData> GetUserDataAsync(BankIdAuthRequestContext authRequestContext, HttpContext httpContext);
```

**Comment by equist** [comment]
Unfortunately I don't believe HttpContext would be sufficient. I'm involved in many scenarios where the domain is the same, so we can't make any conclusion on that, but it rather depending on the client (aka the application using the IdP). Since the request to the IdP where we have the ClientId will result in a brand new request to the BankId area the HttpContext won't have any information about the client or anything from the original request.
The best thing would be if it was possible to pass on extra information through the AuthenticationHandler to the BankIdController. We are now talking about UserVisibleData, but for us it would be really nice to also be able to pass on other information (at least ClientId) so that we could load dynamic stylesheets for branding and other things too.
I could take time for an online meating if this is easier to discuss instead of writing :)

**Comment by PeterOrneholm** [comment]
Great input!

We have those ideas for our "new architecture (#257)" (which has no planned date in our roadmap). I want to redesign it for better multi-tenant support.

Until then, our current solution is to figure this stuff using the HttpContext. I've implemented it for customers by storing the state/tenant in a (secure/encrypted) cookie when the flow begins and then that info is being read when to (for example) choose a certificate and similar settings.
