### ISSUE TITLE
Get Orderref as a txn claim

### ISSUE THREAD

**Issue by equist** [ActiveLogin/ActiveLogin.Authentication#337]
**Is your feature request related to a problem? Please describe.**
If the application that uses ActiveLogin BankId needs to keep an audit trail of the sign-in, it is not possible toady. We can store the completionData and orderRef and correlate it with a user, but it is not possible to correlate it to the exact sign-in. This means if the user sign-in, sign-out and then sign-in again we'll have two orderRef and completionData for the user, but it's not easy to correlate which orderRef corrsponds to which sign-in. Authentication Time is not good enough. Instead it would be nice if it was possible to get the orderRef as a claim on the user. The txn claim could preferably be used for this.

From OpenId Connect for Identity Assurance (https://openid.net/specs/openid-connect-4-identity-assurance-1_0.html):
The txn Claim as defined in [RFC8417] is used in the context of this extension to build audit trails across the parties involved in an OpenID Connect transaction.

IANA (https://www.iana.org/assignments/jwt/jwt.xhtml) list txn as a transaction identifier.

**What area is it related to**
UI and issued user claims.

**Describe the solution you'd like**
A txn claim with the orderRef value should be issued when the user is authenticated.

**Describe alternatives you've considered**
If not always issuing the claim, make a setting to enable the issuance of the txn claim.

**Comment by PeterOrneholm** [comment]
That is great input! I think it should be on by default, but configurable.

I'm thinking something like this to allow for a more flexible Claim handling in the future:

1. Ensure that `BankIdLoginResult` contains the __orderRef__
2. Make `GetClaims` in `BankIdHandler` pluggable

Regarding 2. This could be made in primarily 2 different ways.
1. Add all the default claims and allow for a "TransformClaims" at the bottom. Basically allowing for removing/changing/adding claims given the context available. But you always start with the default setup.
2. Remove all default claim adding handling and move that into a default implementation that can be swapped. A common scenario would then be to inherit from the default implementation and add/remove/change claims doing so (or completely swap the whole implementation).

Solution 2 would be the cleanest I think. Easier to test also.

Any input @equist ?

**Comment by equist** [comment]
I agree that 2 is cleaner and allows full flexibility, but still with an easy default.

**Comment by nallejacobsson** [comment]
I place my vote on solution 2 also. Please make nameidentifier part of the default implementation 😊

**Comment by PeterOrneholm** [comment]
I'm adding this to the 5.0.0 milestone as it seems many of you want this feature.

**Comment by PeterOrneholm** [comment]
We are implementing this now and have read up on the txn claim spec. To issue the txn claim out of the box is a much commitment than we can take on, because of the lines marked below (from the spec). If we were to issue that claim we need to ensure that all the data specified is retreivable by the orderRef, and that very much depends on what data you log / store.

![image](https://user-images.githubusercontent.com/1662918/156587672-23e12274-5bbc-4735-bfd0-1fb7a60c9e4f.png)

What we can do though is to make it very simple for you to implement that yourself. We are now looking at the "extension model" to be able to override/customize the claims issuing yourself. We will ensure that the context provided will contain enough info.

**Comment by PeterOrneholm** [comment]
@equist A draft PR is now available. We still need to write docs and test, but from what you can see - any input?

https://github.com/ActiveLogin/ActiveLogin.Authentication/pull/350

**Comment by equist** [comment]
It looks good! My first reaction was to allow the DefaultBankIdClaimsTransformation method to be overriden, but when I looked at it again, it aw possible to have multiple transformation classes so that will work even better.

I'm thinking, if it would be possible to make the BankIdLoginOptions and the LoginResult more extensible somehow. (for example with something like Items on AuthenticationProperties). I see the difficulty since it is passed as query string parameters, but if possible it would have been easier to extend the possiblity to pass orderref without requiring it to be implemented in the main code. I can also see other scenarios, for example beeing able to pass the clientId down to the login controller (could be used to resolve client specific options, for example custom stylesheets). Also related to passing messages for the purpose of authentication. Just some loose thought spinning in my head, but not fully thought through.

**Comment by PeterOrneholm** [comment]
> It looks good! My first reaction was to allow the DefaultBankIdClaimsTransformation method to be overriden, but when I looked at it again, it aw possible to have multiple transformation classes so that will work even better.

Exactly. You can remove the default implementation if you want, but easiest would be to register your own and just clear/remove the claims you don't want. The advantage of multiple transformations is that different modules can add their own claims transformations.

> I'm thinking, if it would be possible to make the BankIdLoginOptions and the LoginResult more extensible somehow. (for example with something like Items on AuthenticationProperties). I see the difficulty since it is passed as query string parameters, but if possible it would have been easier to extend the possiblity to pass orderref without requiring it to be implemented in the main code. I can also see other scenarios, for example beeing able to pass the clientId down to the login controller (could be used to resolve client specific options, for example custom stylesheets). Also related to passing messages for the purpose of authentication. Just some loose thought spinning in my head, but not fully thought through.

I like the idea. We won't solve that in this PR, but the thoughts are good for a potential new architecture (#257).
