### ISSUE TITLE
Cancel button not enabled on iOS for same-device cancelled authentication

### ISSUE THREAD

**Issue by altenstedt** [ActiveLogin/ActiveLogin.Authentication#400]
**Describe the bug**
On iOS, if a user runs BankID on same-device and cancel the authentication in the BankID app, then the `initialize` function is not run since `sessionOrderRef` is truthy on line 65 in `activelogin-main.ts`.

This means that `enableCancelButton` is not run and the cancel button on the resulting form does not work.

I am guessing that the `enableCancelButton` should run for both cases in the if statement at line 65 in `activelogin-main.ts`.

**What area is it related to**
UI, iOS same-device

**To Reproduce**
1. Open site on Safari on iOS
2. Open BankID on same device
3. Click cancel in the BankID app
4. Click Cancel in the UI

**Expected behavior**
I expect to be redirected to the `cancelReturnUrl`.

**NuGet package version**
6.0.3

**Runtime version**
7.0.3

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 16.3.1
 - Browser: Safari
 - Version: bundled with iOS 16.3.1

**Additional context**
None

**Comment by PeterOrneholm** [comment]
Thanks for reporting! We will look into this later in. If you want to make a PR, that would be very welcome :)

**Comment by altenstedt** [comment]
I did not feel confident enough with the TypeScript code to provide a PR. There seem to be a lot going on that I am not sure how to test for.  But if you can provide just a little guidance, I can try to contribute.  

If I just lift `enableCancelButton` to the top-level as-is, and update `checkStatus` to call `enableCancelButton` in the catch statement, is that roughly correct?  If so, what is the correct value for cancelUrl?
