### ISSUE TITLE
Implement Phone support from API V6

### ISSUE THREAD

**Issue by PeterOrneholm** [ActiveLogin/ActiveLogin.Authentication#404]
**Is your feature request related to a problem? Please describe.**

Phone is a new concept introduced in API V6.0. It allows to initiate an authentication order when the user is talking to the RP over the phone. See section 10.2 in the [Relying Party Guidelines V6.0](https://www.bankid.com/assets/bankid/rp/bankid-relying-party-guidelines-v6.0.pdf) for documentation. 

**What area is it related to**
- API
- Core

**Additional context**
PArt of API V6 (#402) but a very specific new feature so we should implement it separately.

**Comment by vijng** [comment]
Hi @PeterOrneholm, any news on this one?

**Comment by PeterOrneholm** [comment]
This is a feature we don't have any case on ourselves at the moment, so nothing we will prioritize near time. We think features should be built when there is a need with deeper understanding on how it should be used. I think Phone support is a great candidate for a company to sponsor (as was done with other features in Active Login) so we can build it together :)

**Comment by span** [comment]
We are starting to look into this, since it is something we are using for our customer service department.

Has there been any work on it previously that is not linked to this issue or can we start building from a clean slate?

**Comment by PeterOrneholm** [comment]
Great :)

We haven't done any work on this, feel free to suggest an implementation and make PR or let's have a chat if you want to sponsor such feature.

**Comment by vijng** [comment]
Hi Daniel, we have not done any work on this either. But feel free to keep this thread updated as you go along with the implementation, so if possible, we might be able to pitch in.
