### ISSUE TITLE
Error on adding ActiveLogin.Authentication.BankId.AspNetCore nuget package

### ISSUE THREAD

**Issue by kavinchu** [ActiveLogin/ActiveLogin.Authentication#422]
Hi!

I followed the guide to install ActiveLogin.Authentication.BankId.AspNetCore nuget on our server side project. After adding the nuget to our project, we encountered errors when attempting to build the project. These errors were related to a file named tsconfig.js.map which is a read-only file.
![image](https://github.com/ActiveLogin/ActiveLogin.Authentication/assets/11497888/f9552722-e0e2-4bc9-8efa-b3392935a337)

First error we encountered is show in the image below. By adding the tsconfig.ts file we get the above error:
![image](https://github.com/ActiveLogin/ActiveLogin.Authentication/assets/11497888/1b435cdb-c30b-4036-98e1-314eca8f53aa)

Am I missing anything to make it work or is it not supported?

Thanks in advance!

**NuGet package version**
ActiveLogin.Authentication.BankId.AspNetCore 7.0.0

Blazor WASM "hosted" application
.Net 7

**Comment by PeterOrneholm** [comment]
I have seen this before, but thought it was resolved.

Blazor Isn't officially supported, can you try if you would get the same issue in a non Blazor app?

Btw, with Blazor WASM hosted, which one of the models do you mean? Is it Blazor Server or Blazor Web Assembly?

**Comment by kavinchu** [comment]
I created a ASP.NET Empty project with .Net 7.0 Framework and just added ActiveLogin.Authentication.BankId.AspNetCore.
Got the same result:

![image](https://github.com/ActiveLogin/ActiveLogin.Authentication/assets/11497888/86a4e34c-1196-4487-b792-ecd249cea900)

> Btw, with Blazor WASM hosted, which one of the models do you mean? Is it Blazor Server or Blazor Web Assembly?
Blazor Server.

> I have seen this before, but thought it was resolved.

Do you remember how you resolved it? :)

**Comment by PeterOrneholm** [comment]
Thanks for checking!'

We had this in an alpha/beta. To solve it now for you you should be able to remove the "file" that was created (or looks like it is created) in your project explorer in Visual Studio.

I thought we fixed it before releasing the stable version, but maybe we didn't fix it enough :) We'll have a look.

**Comment by kavinchu** [comment]
you are welcome :)
thanks for helping me out!

I don't have any errors now but running the project crashes the iisexpress with Access violation.

> The program '[29564] iisexpress.exe' has exited with code 3221225477 (0xc0000005) 'Access violation'.
> The program '' has exited with code 4294967295 (0xffffffff).
> The thread 0x1 has exited with code 0 (0x0).
> The program 'service-worker.js' has exited with code 4294967295 (0xffffffff).
