### ISSUE TITLE
Flow fails on third party browsers (Chrome/Edge) on iOS when returned from the BankID app

### ISSUE THREAD

**Issue by PeterOrneholm** [ActiveLogin/ActiveLogin.Authentication#433]
**Describe the bug**
We have seen (and been able to reproduce) that when using Chrome/Edge on iOS the flow works fine, but when returned to the browser it (sometimes) displays the error "Load failed". This seems to be a local error on iOS that happens when fetch() fails. Our idea is that this is related to that the browser tries to check the status even though the browser have been put into the "background" and is then prohibited to make a fetch call.

**What area is it related to**
API, UI etc.

**To Reproduce**
1. Choose to sign in
2. Open BankID app
3. Put away phone and wait a while
3. Sign in
4. Go back to Edge/Chrome
5. Error: Load failed

**NuGet package version**
7.0.0

**Additional context**
Suggested solution:
* Add retry logic to the fetch calls
* Check if page is in focus (maybe usinghttps://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API)

**Comment by Abrissirba** [comment]
Do we have more information about the error being thrown by the browser? Message or error code?

**Comment by PeterOrneholm** [comment]
It is "Load failed" that is thrown when calling fetch on iOS Safari, like this:
https://stackoverflow.com/questions/71280168/javascript-typeerror-load-failed-error-when-calling-fetch-on-ios

**Comment by weikkoaejmelaeus** [comment]
It only gives a generic "Load failed" error. I believe the fix is as simple as just to do a retry once on the checkStatus method if it fails.

**Comment by Abrissirba** [comment]
Retry logic might not be that simple. From my understanding you can only get the personal data from BankID once in a session. If you try to check status after that, bakis will return an error.

I am not sure where/when the load fails. The request could arrive at the server which then asks bankid for status. If bankid then returns successfully but the request from the browser fail, the retry will not work since the bakis session already is finished.

**Comment by weikkoaejmelaeus** [comment]
I get you point. However, we seem to have luck on this one that the requests are not actually sent to the server. I did a monkey patch and after the retry was implemented I have not been able to reproduce the "Load failed" error. So while not perfect, I believe that it is a good improvement.

I'll submit a PR next week.
