### ISSUE TITLE
Add support for GrandID SITHS

### ISSUE THREAD

**Issue by PeterOrneholm** [ActiveLogin/ActiveLogin.Authentication#45]
GrandID supports SITHS in addition to BankID. https://e-identitet.se/tjanster/inloggningsmetoder/grandid-api/

Implementing this will require changes in `ActiveLogin.Authentication.GrandId.Api` and `ActiveLogin.Authentication.GrandId.AspNetCore`.

From what I understand It's up to the one implementing it do decide whether to use the dekstop or mobile key. From what I understand, you can't use the mobile app to authenticate a login on your desktop. Therefore, from the consumption point of view, it would make the most sense to just have `.AddSiths()`, supply both keys, and then figure out which one to use depending on what device the user has. We have an implementation for this is the BankID implementation. If you only support one of them, you only supply one key.

The final implementation should then have a public facing API like this:

```csharp
services.AddAuthentication()
        .AddGrandId(builder =>
    {
        builder
            .UseDevelopmentEnvironment()
            .AddBankIdChooseDevice(options =>
            {
                ....
            })
            .AddSiths(options =>
            {
                options.GrandIdDesktopDeviceAuthenticateServiceKey = "UIO";
                options.GrandIdMobileDeviceAuthenticateServiceKey = "ABC";
            });
    });
```

The implementation includes (but is probably not limited to) these files:

## ActiveLogin.Authentication.GrandId.Api

- [ ] Add and implement method `SithsFederatedLoginAsync` to/IGrandIdApiClient.cs and implement in derived classes
- [ ] Add method `SithsGetSessionAsync` to /IGrandIdApiClient.cs and implement in derived classes
- [ ] Add and implement /Models/SithsFederatedLoginFullResponse.cs
- [ ] Add and implement /Models/SithsFederatedLoginRequest.cs
- [ ] Add and implement /Models/SithsFederatedLoginResponse.cs
- [ ] Add and implement /Models/SithsSessionStateFullResponse.cs
- [ ] Add and implement /Models/SithsSessionStateRequest.cs
- [ ] Add and implement /Models/SithsBankIdSessionStateResponse.cs

## ActiveLogin.Authentication.GrandId.AspNetCore

- [ ] Add and implement methods for `.AddSiths()` in /GrandIdAuthenticationBuilderSchemeExtensions.cs
- [ ] Add and implement values in /GrandIdAuthenticationDefaults.cs
- [ ] Add and implement /GrandIdSithsAuthenticationHandler.cs
- [ ] Add and implement /GrandIdSithsAuthenticationOptions.cs
- [ ] Add and implement /GrandIdSithsAuthenticationPostConfigureOptions.cs
- [ ] Add any new claim types to /GrandIdClaimTypes.cs
- [ ] Add new logging events to /GrandIdLoggingEvents.cs
- [ ] Add new logging extensions to /LoggerExtensions.cs

## IdentityServerSample

- [ ] Add samples to Startup.cs

## Docs

- [ ] Update docs with getting started etc.

**Comment by PeterOrneholm** [comment]
Hi @hematmedhelp! Inspired by your PR we have now refactored the GrandID implementation to better support other GrandID "providers" like SITHS. The refactoring allows for side by side implementations that shares code, but can have different options etc. when that applies. I've summarized above how I think it should work and be implemented. Inputs on that?

**Comment by hematmedhelp** [comment]
Looks clear and concise and goes well with the practical flow.

Small nitpick would be 

```
 builder
            .UseDevelopmentEnvironment()
            .AddBankIdChooseDevice(options =>
            {
                ....
            })
            .AddSiths(options =>
            {
                options.GrandIdDesktopDeviceAuthenticateServiceKey = "UIO";
                options.GrandIdMobileDeviceAuthenticateServiceKey = "ABC";
            });
```

If I'm not totally mistaken it should be **AddGrandIdChooseDevice**, not **AddBankIdChooseDevice** :)

**Comment by PeterOrneholm** [comment]
> Looks clear and concise and goes well with the practical flow.

God, thanks!

You that have been working with Siths, is this assumption correct?

> From what I understand It's up to the one implementing it do decide whether to use the dekstop or mobile key. From what I understand, you can't use the mobile app to authenticate a login on your desktop. Therefore, from the consumption point of view, it would make the most sense to just have .AddSiths(), supply both keys, and then figure out which one to use depending on what device the user has.

> If I'm not totally mistaken it should be **AddGrandIdChooseDevice**, not **AddBankIdChooseDevice** :)

I just added it as an example that GrandId should support both BankId and Siths :)

**Comment by PeterOrneholm** [comment]
> I do believe that **AddSiths()** will suffice as in either scenario you could chain them with their own schemes. but the response back to the application should be the same (from what I've gathered from the documentation)

The problem as I see it with two `.AddSiths()` as in your example is that it will be strange to the user. By adding both of them, both will show up as "buttons" for the user, but only one will be valid. If you are on desktop, only desktop sould be shown, if you are on mobile, only mobile should be shown. Tjat's why I propose one `.AddSiths()` that takes the keys for both scenarios and then figures out what flow to use.

**Comment by hematmedhelp** [comment]
> The problem as I see it with two `.AddSiths()` as in your example is that it will be strange to the user. By adding both of them, both will show up as "buttons" for the user, but only one will be valid. If you are on desktop, only desktop sould be shown, if you are on mobile, only mobile should be shown. Tjat's why I propose one `.AddSiths()` that takes the keys for both scenarios and then figures out what flow to use.

Well you would also be specifying the scheme name to be used for the button but I think the incoming client should be restricted to their appropiate providers. I guess if you have a webapplication that serves both desktop and mobiles they'd use the same client - but then you could always do the UI-logic frontend with how you're presenting them.

Then again we're discussing semantics and I just wanted to present an "easier" solution but in the end it doesn't really matter.

**Comment by PeterOrneholm** [comment]
I just had an offline discussion with a colleague that also has used and implemented Siths. We agreed on that in the future this "smart" solution might be a thing, but we would start with the desktop that seems to be the most common (and easiest) one to implement. Then that would look like this:

```csharp
.AddSithsDesktopDevice(options =>
{
     options.GrandIdAuthenticateServiceKey = "UIO";
});
```

And in the future we could add:

```csharp
.AddSithsMobileDevice(options =>
{
     options.GrandIdAuthenticateServiceKey = "UIO";
});
```

and (something auto like):

```csharp
.AddSithsAutoDevice(options =>
{
     options.GrandIdAuthenticateServiceKey = "UIO";
});
```

But let's focus on the Desktop one if that fits your needs for now?

**Comment by hematmedhelp** [comment]
Looks good - and yes, desktop is the one that I need to implement (currently running it as my ugly little fix from the PR).

**Comment by PeterOrneholm** [comment]
We haven't seen or heard any more interest for this in over 1.5 years now, so will close it for now. No plans at the moment to support SITHS.
