### ISSUE TITLE
Add the possibility to pass personal number requirement to sign via BankIdSignProperties

### ISSUE THREAD

**Issue by nallejacobsson** [ActiveLogin/ActiveLogin.Authentication#459]
#445 added the possibility to pass personal number requirement to sign via BankIdFlowOptions (using BankIdFlowService). I would like the same possibility via BankIdSignProperties (using BankIdInitiateSign).

**Comment by nallejacobsson** [comment]
PS. I will have a look at the code and see if I can manage a PR, but time is a bit short now just before summer unfortunately :(

**Comment by elinohlsson** [comment]
Released in [v 10.1.1](https://github.com/ActiveLogin/ActiveLogin.Authentication/releases/tag/v10.1.0).
