### ISSUE TITLE
Check if Styles section defined on the main web project

### ISSUE THREAD

**Issue by nikolaykrondev** [ActiveLogin/ActiveLogin.Authentication#55]
We need to rethink the insertion of Styles section in our Razor Area.
For example in Login.cshtml within BankIdAuthentication area we assume that people use section Style in their _Layout.cshtml, so the code `@section Styles {
    <style type="text/css">
        ...
    </style>
}` will throw an exception if there is no `@RenderSection("Styles", required: false)` in _Layout.cshtml master page.

The solution could be either to insert it in the header directly (which is not recommended since we use Areas) or do the smart-check: if it defined - then we use as it is, otherwise via the header.

**Comment by PeterOrneholm** [comment]
Great finding! Will look at a solution.
