### ISSUE TITLE
Add a sample project for a stand alone MVC application (without IdentityServer)

### ISSUE THREAD

**Issue by rfolkes** [ActiveLogin/ActiveLogin.Authentication#57]
I think there is a need for an MVC sample that doesn't use IdentityServer since it could simplify the understanding of the setup in that scenario. I've created one based on the standard ASP.NET Core MVC 2.1 template (added the same UI for showing Claims as in the MVCClient sample). What do you think - worth adding to the solution?

**Comment by nikolaykrondev** [comment]
Reading my mind :) I agree that there is a need for this and it is much easier to understand.
I also created a standalone project in a separate branch and not yet committed.

**Comment by PeterOrneholm** [comment]
Great, I'd love to see such sample!

Does anyone of you (@rfolkes / @nikolaykrondev) have a one that could be pushed, please do a PR!

I'd vote it should be places in the `.\samples` folder and be called `MvcStandaloneSample`, ok?
