### ISSUE TITLE
Use the same language in buttons defaults for both BankID and GrandID

### ISSUE THREAD

**Issue by nikolaykrondev** [ActiveLogin/ActiveLogin.Authentication#78]
At the moment BankID uses English texts and GranID - Swedish:
![image](https://user-images.githubusercontent.com/5111043/52332325-8c110800-29fa-11e9-860b-78a233887844.png)

**Comment by PeterOrneholm** [comment]
Good catch @nikolaykrondev!

I'd suggest that the default display name should be Swedish, that should be the most used language as BankID is Swedish.

Changes needed:

- `BankIdAuthenticationDefaults.SameDeviceDisplayName` should be set to `"BankID (Denna enhet)"`
- `BankIdAuthenticationDefaults.OtherDeviceDisplayName` should be set to `"BankID (Annan enhet)"`

Is this considered a breaking change, so we have to release it as 2.0.0? I'm not 100% sure, but we are changing a public API by returning a different value. People who use it and expect it to be in English would experience it as a breaking change.

**Comment by Zonnex** [comment]
I guess if we are very strict, it's a breaking change, although I don't imagine many to be heavily affected by it?
