### ISSUE TITLE
Override for Razor Class Library does not work with current partial tag helpers

### ISSUE THREAD

**Issue by nikolaykrondev** [ActiveLogin/ActiveLogin.Authentication#79]
We use the latest `<partial name="" />` tag helper, but somehow it does not work when you override it in the actual MVC project, so the browser renders exactly the tag which means Razor does not recognise it as a valid partial wrapper.

One of the solutions could be to rollback to the old implementation of rendering partials, like `@await Html.PartialAsync("_partial.cshtml")`

Or we can completely get rid of the partials and start using components instead (https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.2). I like this option more, but needs to be tested if Razor engine on the top project can recognise it.

**Comment by PeterOrneholm** [comment]
Thanks @nikolaykrondev!

Do I get it right, that it still supports overridnig a view, but if you want to reference a partial, you need to use the "old" syntax. So, let's say I want do do my own version of `Login.cshtml`, do I need to use this syntax then?

```html
<h1>Custom html etc</h1>
@await Html.PartialAsync("_Login.cshtml")
```

Suggestion would be to do two things:
- Add documentation on how to override template
- Add example on how to override in one of the samples, suggesting the standalone one.

**Comment by Zonnex** [comment]
So after playing around with this a bit, (with various results) we have managed to successfully override the partials.

In the MvcSample, we added the following files and folders. 

```
-Areas
    -BankIdAuthentication
        -Views
            _ViewImports.cshtml
            -BankId
                _LoginForm.cshtml

```
By including the partials in this specific folder we could override whichever partial we wanted, and if we override _Login.cshtml we could have that one call another partial in the same folder.
We added ``` @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers ``` in the _ViewImports.cshtml to get the partials tag helper to work.
We did not manage to get Views/Shared to work.

We can include documentation for this and update the MvcSample to show this.
Are we satisfied with this?

**Comment by Zonnex** [comment]
Another thought is regarding Razor Pages vs "Traditional MVC". I can't seem to get our current structure to work with razor pages, so we would have to pick one?
Is this a case of having the views become it's own package or something?

**Comment by PeterOrneholm** [comment]
> We can include documentation for this and update the MvcSample to show this.
> Are we satisfied with this?

Great work @Zonnex! Yes, that should be cool! Please find something good to override in the MvcSample :)

> Another thought is regarding Razor Pages vs "Traditional MVC". I can't seem to get our current structure to work with razor pages, so we would have to pick one?

Good point. Razor pages are part of MVC, so you can always combine them I guess? If you don't need to override anything you are fine with default setup. If override is needed, probably some more config.

> Is this a case of having the views become it's own package or something?

Not sure what the use case would be? BankID does not work without the views, so there is a quite string relationships between these.

**Comment by Zonnex** [comment]
So I have experimented more with this, and if we would convert to use Razor Pages instead of Controllers, we would make it possible to override our pages from many more folders.

Using a structure like this: 
![image](https://user-images.githubusercontent.com/7324655/53346380-36ec5600-3917-11e9-9c32-834422db1cd6.png)

We can then allow users to override our partials in these places whether or not the calling application is made with Razor Pages or Controllers.:

```
/Areas/BankIdAuthentication/Pages/{0}.cshtml
/Areas/BankIdAuthentication/{0}.cshtml
/Areas/BankIdAuthentication/Pages/Shared{0}.cshtml
/Areas/BankIdAuthentication/Views/Shared/{0}.cshtml
/Pages/BankIdAuthentication/{0}.cshtml
/Pages/{0}.cshtml
/Pages/Shared/{0}.cshtml
/Views/Shared/{0}.cshtml
```
By staying with Controllers, I could only override the partials in 2 places, which I think it was these two

```
/Areas/BankIdAuthentication/{0}.cshtml
/Views/Shared/{0}.cshtml
```

**Comment by PeterOrneholm** [comment]
Good findings. But isn't there it good that you actually need to override them here? I'd see these locations as the most natural places to override them. But, maybe not if working with Razor Pages.

```
/Areas/BankIdAuthentication/{0}.cshtml
/Views/Shared/{0}.cshtml
```

I'm not totally sure if I like to move to Razor pages, but I'm open for discussion on that. I'd vote for keeping this issue related to document and add sample of how it works today, make that step no 1, and then add anoter issue to discuss if we should replace the UI with razor pages. Maybe looking at what Microsoft does for their pages that they embed in packages. I think they use it for some auth stuff as well.

**Comment by Zonnex** [comment]
Opened a new issue for further discussion regarding conversion. Here we simply update the documentation so it describes how to override partials.
