### ISSUE TITLE
The live demo doesn't work. It fails at the step that used to start the bankid app. 

### ISSUE THREAD

**Issue by FrankZhangWeb** [ActiveLogin/ActiveLogin.Authentication#8]
Hi Team,

It seems the live demo doesn't work.

After I enter the "Personal Identity Number", it goes to the start the bank id app.
Then I open the bankid app on my mobile, but it doesn't let me enter the password. 

It got stuck at the step "Start your BankID app", and then failed.
"The BankID app is not responding. Please check that the program is started and that you have internet access. If you don’t have a valid BankID you can get one from your bank. Try again.".

Can you kindly confirm?

Thanks.

**Comment by fredrik-lundin** [comment]
Hi Frank,

Thanks for trying out Active login! We are happy to help you, but to be able to do that, we would love to get some more information from you. For example:

Are you using the **dev**, **test** och **production** environment?

What nuget packages are you using? All in with the asp.net core package or do you have a custom solution where you just use the `BankId.Api` package?

**Comment by fredrik-lundin** [comment]
Hmm, that's very strange. I tried both live demos now and they seem to work fine for me. Can you verify that your BankID application is working with other services on your phone?

**Comment by FrankZhangWeb** [comment]
It's really strange.
I tried and it works fine on the site "https://demo.bankid.com".

The following are the detail steps that I took on the demo site.
1, open the demo site. 
https://al-samples-identityserver.azurewebsites.net/BankIdAuthentication/Login?returnUrl=%2Fsignin-bankid 
2, Select "BankId"
3, Enter the "Personal Identity Number"
Actually, what I'm use is a test account (199804210434), I generated the "Personal Identity Number" from a site.
On the demo site, I enter the Personal Identity Number as "980421-0434" and it always in the status "Start your bankid app", after a while, it fails.

Are there any wrong with my steps?
Any suggestion for this?

Thanks.

**Comment by FrankZhangWeb** [comment]
![test](https://user-images.githubusercontent.com/38204951/45206623-09074c80-b2b8-11e8-89e9-27d210633582.png)

**Comment by fredrik-lundin** [comment]
Are you pressing _Log in with a Test BankID_ when you try it out on [https://demo.bankid.com](https://demo.bankid.com)? My guess it that your test account is only valid on the BankID test environment. 

The live demo site we are providing is going against production BankID, meaning a test account will not work. Is it possible for you to try it out with your real BankID (if you have one, of course).

**Comment by fredrik-lundin** [comment]
In the [readme file](https://github.com/ActiveLogin/ActiveLogin.Authentication/blob/master/README.md) there is a section called **2.2 Try it out with Bank ID test environment**. Take a look at that step by step guide and see if it helps. That guide is for using Azure key vault though, if you can't/don't want to do that, there are some small steps that will differ. 

Let us know if you need any more help!

**Comment by PeterOrneholm** [comment]
Hi @FrankZhangWeb! Did the suggested solution from @fredrik-lundin? If so, I'd like to close this issue, otherwise assist you in getting it to work.

**Comment by PeterOrneholm** [comment]
Closing this issue now.
