### ISSUE TITLE
Grattis & docs

### ISSUE THREAD

**Issue by haf** [ActiveLogin/ActiveLogin.Authentication#81]
Congratulations and thank you for this release.

I was hoping to get a README showing basic usage when you like me, don't use the ASP.Net Core platform. What is the "core" library's API and what is a simple usage of it? Or alternatively (after seeing that there's *a lot* of code specific to ASP.Net) perhaps this can be deployed as a k8s/docker container and/or be part of an authentication flow being an OpenId Connect IdP? In that case, could my app could be RP and receive a JWT?

**Comment by PeterOrneholm** [comment]
Thanks @haf! We are also glad to have released our first version :)

That's great feedback! I'll make sure to get more on this topic in the README. Below are my initial ideas, please have input!

The easiest way, if you can't use ASP.NET Core, is to use deploy some kind of OpenId Connect IdP as you say. We recommend Identity Server 4 that also runs on core. If it's a possibility to run the IdP in Azure (client can still be somewhere else), we have a ready template do deploy this. The docs is a bit narrow on only suggesting this for storing certificates, but the [template does setup the rest as well](https://github.com/ActiveLogin/ActiveLogin.Authentication/blob/master/docs/getting-started-bankid.md#storing-certificates-in-azure ).
[Our samples](https://github.com/ActiveLogin/ActiveLogin.Authentication#can-i-try-out-a-live-demo-of-the-samples) uses this template.

Independent on whether or not Azure is an alternative, I'd love to have a minimal IdP that is Dockerized and ready to be used in a container scenario. I'd even suggest we change our current samples to use containers instead when running in Azure. I'l file an issue on this.

And, finally, if you want to use it in other .NET scenarios there are still a few things that you can use as long as you can run .NET Standard 2.0 or .NET Framework 4.6.1 (we compile for both as per MIcrosofts recommendation)

First of all, we extracted the handling (parse/validate/normalize) of Swedish personal identity numbers into its own library. Written in F# but can be used form any language in .NET of course:
- https://github.com/ActiveLogin/ActiveLogin.Identity
- https://www.nuget.org/packages/ActiveLogin.Identity.Swedish/

Then, we don't have a core package as that, but the wrappers of the API:s are extracted into own packages to allow for other integrations to use them. A few lines of [docs can be found here](https://github.com/ActiveLogin/ActiveLogin.Authentication#do-i-need-to-use-your-aspnet-core-auth-provider-or-can-just-use-the-api).
- https://github.com/ActiveLogin/ActiveLogin.Authentication/tree/master/src/ActiveLogin.Authentication.BankId.Api
- https://github.com/ActiveLogin/ActiveLogin.Authentication/tree/master/src/ActiveLogin.Authentication.GrandId.Api
- https://www.nuget.org/packages/ActiveLogin.Authentication.BankId.AspNetCore/
- https://www.nuget.org/packages/ActiveLogin.Authentication.GrandId.AspNetCore/

Tests available here:
- https://github.com/ActiveLogin/ActiveLogin.Authentication/tree/master/test/ActiveLogin.Authentication.BankId.Api.Test
- https://github.com/ActiveLogin/ActiveLogin.Authentication/tree/master/test/ActiveLogin.Authentication.GrandId.Api.Test

A lot of the rest of the code is very specific to how ASP.NET Core wants you to do the authentication integration, even though there are a few things that could be refactored into it's own Core package. If you are looking at using it for another scenario, please keep us informed and see if we can refactor it!

**Comment by haf** [comment]
Awesome that you're using F#. I'm using Suave as my web server (obviously ;)), so to see more people using F# is great.

I'm in Google Cloud but primarily, I'm in Kubernetes with no cloud-specific infrastructure in use; so it's all k8s/docker/linux: https://gist.github.com/haf/1078452fbbee851c63733cee6c45597b for us.

After doing a very thurough review of the OIDC platforms available, we decided to use https://github.com/ory/hydra which is both certified and has a plethora of tests, much more than IdentityServer. I know from experience that unit testing your software gives much better results, and this is particularly important in security-critical software.

Perhaps we can create a Helm chart for this project? I'm happy to spend some time with you and help you [get started](https://github.com/haf/linux-intro-course/blob/master/chapter-04/README.md#starting-minikube) if you want help (I'm in STHLM). It can be done in an hour and will really help your uptake.

**Comment by PeterOrneholm** [comment]
Great idea! We are also in Stockholm! Let's arrange a lunch and some hands on work at our office :) I'll make sure @viktorvan joins, who is our main contributor for the  F# parts.

Thanks for the info on Hydra, looks good!

Please drop me an email at peter [at] orneholm.com so we can arrange the details.

**Comment by PeterOrneholm** [comment]
Sorry for no update on the docker/Helm stuff. We have had to prioritize a few other things.
I think the issue #82 replaces this one, so I'll close this.

@haf Would you still be interested in this solution? Should we prioritize the docker stuff for fall?
