### ISSUE TITLE
Add support for sign in BankId api client

### ISSUE THREAD

**Issue by ellinge** [ActiveLogin/ActiveLogin.Authentication#84]
The BankId API client only expose the "auth" method but not the similar "sign" with the extra properties in the request as described in **14.1.2 Additional Parameters for sign**.
I know the package is focused on Authentication, but I think it should expose the sign-functionality as well since it's almost there.

**Comment by PeterOrneholm** [comment]
Great suggestion and thanks for the PR! I've added a few comments.

**Comment by PeterOrneholm** [comment]
Fixed in #85.

**Comment by PeterOrneholm** [comment]
Finally released :)
https://www.nuget.org/packages/ActiveLogin.Authentication.BankId.Api/2.0.0-rc-1

Please give it a try before we go 2.0.0!

**Comment by ellinge** [comment]
Ping @PeterOrneholm 
![bild](https://user-images.githubusercontent.com/17863113/57050505-35c00800-6c7d-11e9-91bd-2ba5a1bb7e39.png)

Seems to be working fine. Logged in as well before signing.

**Comment by PeterOrneholm** [comment]
> Seems to be working fine. Logged in as well before signing.

Nice! Will try a few things before going 2.0.0 sharp. Thanks for testing the RC!
