### ISSUE TITLE
Support third party browsers on iOS

### ISSUE THREAD

**Issue by PeterOrneholm** [ActiveLogin/ActiveLogin.Authentication#86]
Inspired by #83 

## Problem

On iOS, you are required to set a returnUrl that the BankID iOS app will return the user to once signed in. When iOS always launches a URL it will always be launched in the built in browser, Safari. If the session is initiated in a third party browser like Chrome or Firefox, it will not succeed as the login has to be finihsed in the same browser (and that) that it was initiated in.

On Android this is not an issue as when returnUrl is set to null, documented in "3.1.2 Parameters in the Start URL" of the [BankID documentation](https://www.bankid.com/assets/bankid/rp/bankid-relying-party-guidelines-v3.2.1.pdf) it will automatically launch the previously used app, so it would handle Chrome, Firefox or even custom apps.

## Solution 

We could detect (`IBankIdSupportedDeviceDetector`) when the user is running iOS and a known third party browser, and then use a browser prefix.

- [Chrome on iOS](https://developer.chrome.com/multidevice/ios/links): googlechromes://
- [Firefox on iOS](https://github.com/mozilla-mobile/firefox-ios-open-in-client): firefox://open-url?url=
- [Edge on iOS](https://stackoverflow.com/a/51109646/105581): microsoft-edge-https://

Any other browsers that we can and should support?

If you need to support a custom scheme, like for your own app, I'd recommend to implement a custom `IBankIdLauncher` that would handle that scenario. If this is a common scenario, we could build it in and let it be configured.

**Comment by Zonnex** [comment]
Based on offline discussion, we'll wait with this one until someone has issues with this.
