### ISSUE TITLE
Convert Razor Class Library controllers to Razor Pages

### ISSUE THREAD

**Issue by Zonnex** [ActiveLogin/ActiveLogin.Authentication#91]
As suggested in #79, if we would convert our controllers to Razor Pages, we would make it possible to override our partials in more places than now.
Currently there seems to be only 2 folders where our partials can be overridden, and it doesn't match the folder structure you use with Razor pages.

Staying with controllers, the users have to match the old folder style.
If we convert, we support traditional MVC folder structure and Razor pages folder structure.

**Comment by PeterOrneholm** [comment]
Closed as (maybe) part of #162 instead.
